# Use root/example as user/password credentials
version: '3.1'

services:
  rabbit-mq:
    image: rabbitmq:3.8.0-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 1433:1433    # Important: In a production environment your should remove the external port
    volumes:
      - abbyysync-sql-data:/data
volumes:
    mongodb:
    mongodb_config:
    abbyysync-sql-data: